require:
  - rubocop-performance

AllCops:
  Exclude:
    - '**/bin/**/*'
Metrics/AbcSize:
  Max: 30
Style/BlockDelimiters:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - '**/lib/**/*.rake'
Metrics/ClassLength:
  Max: 150
Style/Lambda:
  Exclude:
    - 'app/models/**/*'
Layout/LineLength:
  Max: 80
Metrics/MethodLength:
  Max: 15
Metrics/ModuleLength:
  Max: 150
Naming/FileName:
  Exclude:
    - '**/Guardfile'
    - '**/Capfile'
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/Documentation:
  Exclude:
    - '**/db/migrate/*'
Style/EvalWithLocation:
  Enabled: false
