require: rubocop-rspec

AllCops:
  Exclude:
    - '**/bin/**/*'
AbcSize:
  Max: 30
BlockDelimiters:
  Enabled: false
BlockLength:
  Exclude:
    - '**/spec/**/*'
    - '**/app/views/**/*.jbuilder'
    - '**/lib/**/*.rake'
    - '**/config/routes.rb'
    - '**/config/god*'
    - '**/config/environments/*'
ClassLength:
  Max: 150
Lambda:
  Exclude:
    - 'app/models/**/*'
LineLength:
  Max: 80
Output:
  Exclude:
    - '**/*.rake'
    - '**/rake_support.rb'
MethodLength:
  Max: 15
ModuleLength:
  Max: 150
FileName:
  Exclude:
    - '**/Guardfile'
    - '**/Capfile'
Lint/AmbiguousBlockAssociation:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
Style/Documentation:
  Exclude:
    - '**/db/migrate/*'
RSpec/ExampleLength:
  Max: 15
RSpec/NestedGroups:
  Max: 4
