# frozen_string_literal: true

require: rubocop-rspec

AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
    - '**/*.rake'
    - '**/*.jbuilder'
    - '**/*.gemspec'
    - '**/*.rb'
  Exclude:
    - '**/db/schema.rb'
    - '**/script/**/*'
    - '**/vendor/assets/**/*'
    - '**/bin/**/*'
    - '**/gems/**/*'
    - '**/node_modules/**/*'
    - '**/app/services/diagram/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
AbcSize:
  Max: 30
BlockDelimiters:
  Enabled: false
BlockLength:
  Exclude:
    - '**/admin/**/*'
    - '**/spec/**/*'
    - '**/app/views/**/*.jbuilder'
    - '**/lib/**/*.rake'
    - '**/config/routes.rb'
    - '**/config/god*'
    - '**/config/environments/*'
ClassLength:
  Max: 150
Lambda:
  Exclude:
    - 'app/models/**/*'
LineLength:
  Max: 80
  Exclude:
    - 'config/initializers/content_security_policy.rb'
Output:
  Exclude:
    - '**/*.rake'
    - '**/rake_support.rb'
MethodLength:
  Max: 15
ModuleLength:
  Max: 150
FileName:
  Exclude:
    - '**/Guardfile'
    - '**/Capfile'
Lint/AmbiguousBlockAssociation:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
Style/Documentation:
  Exclude:
    - '**/db/migrate/*'
Naming/UncommunicativeMethodParamName:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
RSpec/NestedGroups:
  Max: 4
