require:
  - rubocop-performance

AllCops:
  Exclude:
    - '**/bin/**/*'
AbcSize:
  Max: 30
BlockDelimiters:
  Enabled: false
BlockLength:
  Exclude:
    - '**/spec/**/*'
    - '**/lib/**/*.rake'
ClassLength:
  Max: 150
Lambda:
  Exclude:
    - 'app/models/**/*'
LineLength:
  Max: 80
Output:
  Exclude:
    - '**/*.rake'
    - '**/rake_support.rb'
MethodLength:
  Max: 15
ModuleLength:
  Max: 150
FileName:
  Exclude:
    - '**/Guardfile'
    - '**/Capfile'
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/Documentation:
  Exclude:
    - '**/db/migrate/*'
Style/EvalWithLocation:
  Enabled: false
