# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 878457b0d8810c72620e5e2afc7ccef6df3cd12a68f180f98ccdfd15a268bdb157577094dc8b77c8da105aae2f95a8a974a190fe3eea1f34c452c9ce8c6ceae4

test:
  secret_key_base: 54608a4fb385ea3f3e2f37ef231e37da8a7015a208ec5cfa60b9c077f84371efaf62d6aeae97baa8323717ab7cb75bd9da51858d8c3b2f15011725cebbcad191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
